apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-django-db-deployment
  namespace: dev-django-api
spec:
  selector:
    matchLabels:
      app: dev-django-db
  replicas: 2
  template:
    metadata:
      labels:
        app: dev-django-db
    spec:
      containers:
        - name: dev-django-db
          image: postgres:16
          env:
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_DB
              value: postgres
          ports:
            - containerPort: 5432
